# Generated by Django 3.0.7 on 2020-07-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200708_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('payment', models.CharField(max_length=50, verbose_name='Meio de pagamento')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
